# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koyeb < Formula
  desc ""
  homepage "https://koyeb.com"
  version "3.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.5.1/koyeb-cli_3.5.1_darwin_amd64.tar.gz"
      sha256 "d68b921fcc2d82a0c7d2dd43ff7a6647230e324e7324833981afbaa99f0dfbde"

      def install
        bin.install "koyeb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.5.1/koyeb-cli_3.5.1_darwin_arm64.tar.gz"
      sha256 "733d22bd218962aef5f278204e6a167cae1d9d99400073c2d0dd9fe157023242"

      def install
        bin.install "koyeb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.5.1/koyeb-cli_3.5.1_linux_arm64.tar.gz"
      sha256 "7e59adb17bb970524e9e97e7ec57ad85ea6c4967d5ec55594a367f86a5259065"

      def install
        bin.install "koyeb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.5.1/koyeb-cli_3.5.1_linux_amd64.tar.gz"
      sha256 "f5e3043eff9bb50d73a71bdde212175d28250c784aab52c48c320f19bb1a8e93"

      def install
        bin.install "koyeb"
      end
    end
  end

  test do
    system "#{bin}/koyeb version"
  end
end
