# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KoyebCli < Formula
  desc ""
  homepage "https://koyeb.com"
  version "2.0.0-rc1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v2.0.0-rc1/koyeb-cli_2.0.0-rc1_darwin_amd64.tar.gz"
      sha256 "0785d8efcb37808a499e57934eea8a2168c521da7090e215aeee7b97fe0de8fd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v2.0.0-rc1/koyeb-cli_2.0.0-rc1_linux_amd64.tar.gz"
      sha256 "7d90f2833636efa78c5e5161d0378aedd8b3f476b1eabd3bbf85dae2ac900d55"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v2.0.0-rc1/koyeb-cli_2.0.0-rc1_linux_arm64.tar.gz"
      sha256 "cb69c0769fec8027713d683b3aef37d40b7ff344352407b480dcb311cb41d2f2"
    end
  end

  def install
    bin.install "koyeb"
  end

  test do
    system "#{bin}/koyeb version"
  end
end
