# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koyeb < Formula
  desc ""
  homepage "https://koyeb.com"
  version "3.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.1.1/koyeb-cli_3.1.1_darwin_arm64.tar.gz"
      sha256 "621e117e2007cc0664769550de4bdeec09ca9284bfaba194466ce36fc4b62a5e"

      def install
        bin.install "koyeb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.1.1/koyeb-cli_3.1.1_darwin_amd64.tar.gz"
      sha256 "d773c836264cb36d0dc2de0294a45f6ab9aff3c8024a503eb85134eaa2a08172"

      def install
        bin.install "koyeb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.1.1/koyeb-cli_3.1.1_linux_amd64.tar.gz"
      sha256 "9aaffdcb6fcc6fa918be4e58482cb474eb2c8da016081b3d61dc4563cd17c1c5"

      def install
        bin.install "koyeb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v3.1.1/koyeb-cli_3.1.1_linux_arm64.tar.gz"
      sha256 "4beb630463f3e03245c2596e6a93106804b0ba75d3ff2acc50f52b7bfcc747b9"

      def install
        bin.install "koyeb"
      end
    end
  end

  test do
    system "#{bin}/koyeb version"
  end
end
