# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KoyebCli < Formula
  desc ""
  homepage "https://koyeb.com"
  version "1.3.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v1.3.0/koyeb-cli_1.3.0_darwin_amd64.tar.gz"
      sha256 "14b06dfda6d6ab549aae0b22af0b11f8f3bcad78f55f0090ffd068607813055f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v1.3.0/koyeb-cli_1.3.0_linux_amd64.tar.gz"
      sha256 "5422c7c23b24c65f42d19f88fe70c7f9b59d5e3db0e9eeeeaf4a8538f3a37a23"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koyeb/koyeb-cli/releases/download/v1.3.0/koyeb-cli_1.3.0_linux_arm64.tar.gz"
      sha256 "968330ec531bbd666d2662a3ac7f3a9701f939ae36b1833350d39607d9c237d5"
    end
  end

  def install
    bin.install "koyeb"
  end

  test do
    system "#{bin}/koyeb version"
  end
end
