# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koyeb < Formula
  desc ""
  homepage "https://koyeb.com"
  version "4.2.0"

  on_macos do
    on_intel do
      url "https://github.com/koyeb/koyeb-cli/releases/download/v4.2.0/koyeb-cli_4.2.0_darwin_amd64.tar.gz"
      sha256 "5eddf09969c5bbefdcc2dc9cf5b9234af218577efc9a3de5c3fa25b9c3f94bf1"

      def install
        bin.install "koyeb"
      end
    end
    on_arm do
      url "https://github.com/koyeb/koyeb-cli/releases/download/v4.2.0/koyeb-cli_4.2.0_darwin_arm64.tar.gz"
      sha256 "245e1cdbb4a532c4be1dd73d29aa6177c9b9c5f842daf264ecad29d39b347025"

      def install
        bin.install "koyeb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koyeb/koyeb-cli/releases/download/v4.2.0/koyeb-cli_4.2.0_linux_amd64.tar.gz"
        sha256 "a51c93545ecb8d5265fdffbefe936fd1508b94d9eb004030c4cede09647d58f5"

        def install
          bin.install "koyeb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koyeb/koyeb-cli/releases/download/v4.2.0/koyeb-cli_4.2.0_linux_arm64.tar.gz"
        sha256 "e9b7542402b8f3bc5893cef96d349791249f4bb6ae6d0cd0240185ea888b3554"

        def install
          bin.install "koyeb"
        end
      end
    end
  end

  test do
    system "#{bin}/koyeb version"
  end
end
